# Use Node.js image
FROM node:18.7.0-alpine3.16

# Create app directory
WORKDIR /frontend

# Install yarn
# RUN npm install -g yarn

# Install create-react-app via yarn
RUN yarn global add create-react-app
